import type { Actor } from "../domain/accounts";
import { buyerLabel } from "../domain/buyers";
import { DomainError,type State } from "../domain/model";
import { financialReport,get,invoiceBalance,invoiceTotal,money,scopeState } from "../domain/selectors";
export const escape=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
function table(head:string[],rows:unknown[][]){return `<table><thead><tr>${head.map(h=>`<th>${escape(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${escape(c)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;}
function reportContent(report:ReturnType<typeof financialReport>){return table(["Akun","Debit","Kredit","Saldo debit / (kredit)"],[...report.accounts.map(a=>[a.name,money(a.debit),money(a.credit),money(a.debit-a.credit)]),["Total",money(report.debit),money(report.credit),money(report.debit-report.credit)]]);}
export function documentHTML(raw:State,actor:Actor,kind:string,id:string){if(actor.role==="admin"||(kind==="invoice"&&["staf","kurir"].includes(actor.role)))throw new DomainError("Dokumen tidak dapat diakses.",403);const s=scopeState(raw,actor);let title="",subtitle="",content="";
 if(kind==="shipment"){const sh=get(s.shipments,id),o=get(s.orders,sh.orderId);title=`Surat Jalan ${sh.number}`;subtitle=`${buyerLabel(s,o)} · ${sh.date} · ${sh.status}`;const ls=s.shipmentLines.filter(l=>l.shipmentId===sh.id);content=`<p>Pesanan: ${escape(o.number)}<br>Alamat: ${escape(o.address)}<br>Kendaraan: ${escape(sh.vehicle)}<br>Kurir: ${escape(raw.users.find(u=>u.id===sh.courierId)?.name)}</p>`+table(["Barang","Satuan","Disiapkan / dikirim","Diterima","Kembali"],ls.map(l=>{const p=get(s.products,get(s.orderLines,l.orderLineId).productId);return [p.name,p.unit,l.qty,l.accepted,l.returned];}))+`<p>Penerima: ${escape(sh.receiver||"Belum dikonfirmasi")}<br>Bukti: ${escape(sh.evidence||"Belum ada")}<br>Catatan: ${escape(sh.note)}</p><div class="sign"><p>Petugas Unit Toko<br><br><br>__________________</p><p>Penerima<br><br><br>__________________</p></div>`;
 }else if(kind==="invoice"){const i=get(s.invoices,id);title=`Invoice ${i.number}`;subtitle=`${buyerLabel(s,i)} · terbit ${i.date} · jatuh tempo ${i.dueDate}`;const ls=s.invoiceLines.filter(l=>l.invoiceId===i.id);content=table(["Barang / Surat Jalan","Jumlah","Harga","Subtotal","Pajak"],ls.map(l=>{const sl=get(s.shipmentLines,l.shipmentLineId),sh=get(s.shipments,sl.shipmentId),p=get(s.products,get(s.orderLines,sl.orderLineId).productId);return [`${p.name} · ${sh.number}`,l.qty,money(l.price),money(l.subtotal),money(l.tax)];}))+`<p class="total">Total: ${money(invoiceTotal(s,i.id))}<br>Sisa piutang saat dicetak: ${money(invoiceBalance(s,i.id))}</p><p>${escape(i.taxNote)}</p>`+table(["Tanggal alokasi","Referensi pembayaran","Nilai"],s.allocations.filter(a=>a.invoiceId===i.id).map(a=>[a.date,get(s.payments,a.paymentId).reference||get(s.payments,a.paymentId).payer,money(a.amount)]))+table(["Tanggal koreksi","Alasan","Nota kredit disetujui"],s.credits.filter(c=>c.invoiceId===i.id&&c.status==="approved").map(c=>[c.date,c.reason,money(c.amount)]));
 }else if(kind==="purchase"){const p=get(s.purchases,id);title=`Pengadaan ${p.number}`;subtitle=`${p.kind} · ${p.date} · ${get(s.suppliers,p.supplierId).name}`;content=table(["Barang","Pesan","Terima","Harga beli","Nilai"],s.purchaseLines.filter(l=>l.purchaseId===p.id).map(l=>[get(s.products,l.productId).name,l.qty,l.received,money(l.cost),money(l.qty*l.cost)]))+`<p>${escape(p.note)}</p>`;
 }else if(kind==="report"||kind==="period"){if(!["kepala","laporan","penagihan","pimpinan","akuntansi"].includes(actor.role))throw new DomainError("Laporan tidak dapat diakses.",403);if(kind==="period"){const p=get(s.periods,id);title=`Laporan periode ${p.id}`;subtitle=`Versi ${p.revision} · ${p.status}${p.closedAt?` · dikunci ${p.closedAt}`:""}`;content=reportContent((p.snapshot||financialReport(s,p.id+"-31")) as ReturnType<typeof financialReport>);}else{if(!/^\d{4}-\d{2}-\d{2}$/.test(id))throw new DomainError("Tanggal tidak valid.");title="Laporan gabungan Unit Toko";subtitle=`Saldo kumulatif sampai ${id}`;content=reportContent(financialReport(s,id));}
 }else throw new DomainError("Dokumen tidak ditemukan.",404);
 return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>body{font:14px/1.6 Arial,sans-serif;color:#183d49;margin:32px auto;max-width:1000px;padding:0 24px}header{border-bottom:3px solid #087f8c;padding-bottom:20px}h1{font-size:25px;margin:14px 0 4px}p{white-space:pre-line}table{width:100%;border-collapse:collapse;margin:25px 0;text-align:left}th,td{border-bottom:1px solid #dce8ec;padding:10px;vertical-align:top}th{background:#edf5f6;font-size:12px}.total{text-align:right;font-size:18px;font-weight:bold}.sign{display:flex;justify-content:space-around;margin:40px 0}footer{border-top:1px solid #dce8ec;margin-top:35px;padding-top:14px;font-size:12px;color:#56727d}button{background:#087f8c;color:white;border:0;padding:12px 20px;border-radius:6px;cursor:pointer;float:right}@media print{button{display:none}body{margin:0;padding:0;font-size:11px}thead{display:table-header-group}tr{break-inside:avoid}h1{font-size:20px}@page{size:A4;margin:15mm}}</style></head><body><button onclick="window.print()">Cetak / simpan PDF</button><header><b>UNIT TOKO · PENJUALAN & PENGIRIMAN</b><h1>${escape(title)}</h1><p>${escape(subtitle)}</p></header>${content}<footer>DEMO CAPSTONE · Data dan transaksi simulasi · Bukan dokumen penagihan resmi.<br>Dicetak oleh ${escape(actor.name)} · ${escape(new Date().toLocaleString("id-ID",{timeZone:"Asia/Jakarta"}))} WIB</footer></body></html>`;
}
export function reportCSV(s:State,end:string){const report=financialReport(s,end);const rows:(string|number)[][]=[["Laporan gabungan Unit Toko — data simulasi"],["Saldo kumulatif sampai",end],["Akun","Debit","Kredit","Saldo debit/(kredit)"],...report.accounts.map(a=>[a.name,a.debit,a.credit,a.debit-a.credit]),["Total",report.debit,report.credit,report.debit-report.credit],[],["Jurnal","Tanggal","Keterangan","Akun","Debit","Kredit"],...report.journals.flatMap(j=>s.journalLines.filter(l=>l.journalId===j.id).map(l=>[j.id,j.date,j.description,l.account,l.debit,l.credit]))];return "\uFEFF"+rows.map(row=>row.map(v=>`"${(typeof v==="string"&&/^[=+@\-\t\r]/.test(v)?"'"+v:String(v)).replace(/"/g,'""')}"`).join(",")).join("\r\n");}
