import { DomainError } from "../domain/model";
import type { Actor } from "../domain/accounts";
import { database,ensureSeed } from "./repository";
import { digest } from "./security";
export function json(data:unknown,status=200,headers:Record<string,string>={}){return Response.json(data,{status,headers:{"Cache-Control":"no-store",...headers}});}
export function errorResponse(err:unknown){if(err instanceof DomainError)return json({error:err.message},err.status);console.error("UnitToko:",err);return json({error:"Layanan data sedang tidak tersedia. Isian Anda tetap ada; silakan coba kembali."},503);}
export function sameOrigin(request:Request){const origin=request.headers.get("origin"),expected=new URL(request.url);expected.host=request.headers.get("host")||expected.host;if(origin&&origin!==expected.origin)throw new DomainError("Permintaan berasal dari alamat lain.",403);const fetchSite=request.headers.get("sec-fetch-site");if(fetchSite==="cross-site")throw new DomainError("Permintaan lintas situs ditolak.",403);}
export async function body(request:Request){sameOrigin(request);if(Number(request.headers.get("content-length")||0)>100000)throw new DomainError("Permintaan terlalu besar.",413);const text=await request.text();if(text.length>100000)throw new DomainError("Permintaan terlalu besar.",413);try{return JSON.parse(text);}catch{throw new DomainError("Format data tidak valid.");}}
export async function currentActor(request:Request):Promise<Actor>{const raw=request.headers.get("cookie")?.match(/(?:^|;\s*)toko_session=([^;]+)/)?.[1];if(!raw)throw new DomainError("Silakan masuk untuk melanjutkan.",401);await ensureSeed();const id=await digest(raw),db=database();const row=await db.prepare("SELECT u.payload FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?").bind(id,Date.now()).first<{payload:string}>();if(!row)throw new DomainError("Sesi berakhir. Silakan masuk kembali.",401);const user=JSON.parse(row.payload) as Actor;if(!user.active)throw new DomainError("Akun tidak aktif.",403);return user;}
export function sessionCookie(token:string,request:Request,maxAge=28800){return `toko_session=${token}; HttpOnly; Path=/; SameSite=Strict; Max-Age=${maxAge}${new URL(request.url).protocol==="https:"?"; Secure":""}`;}
