import {readFileSync} from "node:fs";
const accounts=JSON.parse(readFileSync(".data/demo-accounts.json","utf8"));
import assert from "node:assert/strict";
const base=process.env.TOKO_TEST_URL||"http://127.0.0.1:3000";
if(new URL(base).hostname!=="localhost"&&new URL(base).hostname!=="127.0.0.1")throw new Error("Smoke mutasi hanya untuk demo lokal.");
const sessions=new Map();
async function request(who,path,options={}){const headers={...options.headers,...(sessions.has(who)?{cookie:sessions.get(who)}:{})};return fetch(base+path,{...options,headers});}
async function login(who){const r=await fetch(base+"/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(accounts.find(a=>a.email===who+"@unit-toko.demo"))});assert.equal(r.status,200,await r.clone().text());sessions.set(who,r.headers.get("set-cookie").split(";")[0]);}
async function state(who){const r=await request(who,"/api/state");assert.equal(r.status,200);return (await r.json()).state;}
async function action(who,type,data,id=crypto.randomUUID()){const r=await request(who,"/api/commands",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,type,data})});assert.equal(r.status,200,await r.clone().text());return r.json();}
for(const who of ["pic-a","pic-b","kepala","staf","kurir","penagihan","laporan"])await login(who);
let s=await state("staf");const product=s.products.find(p=>p.id==="air")||s.products[0];const order=await action("pic-a","order.create",{neededAt:new Date().toISOString().slice(0,10),note:"Uji alur website — DEMO",lines:[{productId:product.id,qty:2}]});await action("kepala","order.review",{id:order.id,approve:true});s=await state("staf");const line=s.orderLines.find(l=>l.orderId===order.id);await action("staf","stock.reserve",{orderLineId:line.id,qty:2});const sh=await action("staf","shipment.create",{orderId:order.id,courierId:"kurir",vehicle:"DEMO-UJI",lines:[{orderLineId:line.id,qty:2}]});const token=crypto.randomUUID();const dispatch=await Promise.all([action("kurir","shipment.dispatch",{id:sh.id},token),action("kurir","shipment.dispatch",{id:sh.id},token)]);assert.equal(dispatch[0].id,dispatch[1].id);s=await state("staf");const sl=s.shipmentLines.find(l=>l.shipmentId===sh.id);await action("pic-a","shipment.receive",{id:sh.id,lines:[{id:sl.id,accepted:2}]});await action("staf","sale.finalize",{id:sh.id});const invoice=await action("penagihan","invoice.issue",{divisionId:"div-ops",dueDate:new Date(Date.now()+30*864e5).toISOString().slice(0,10),lines:[{shipmentLineId:sl.id}]});const total=2*line.price;const pay=await action("pic-a","payment.record",{amount:total,payer:"PIC demo",reference:"TEST-"+order.id.slice(0,8)});
const form=new FormData();form.set("scope","payment");form.set("targetId",pay.id);form.set("file",new Blob([readFileSync("public/images/products/water.png")],{type:"image/png"}),"bukti-simulasi.png");const uploaded=await request("pic-a","/api/attachments",{method:"POST",body:form});assert.equal(uploaded.status,201,await uploaded.clone().text());const attachment=await uploaded.json();assert.equal((await request("pic-a",`/api/attachments/${attachment.id}`)).status,200);assert.equal((await request("pic-b",`/api/attachments/${attachment.id}`)).status,404);
await action("penagihan","payment.verify",{id:pay.id});await action("penagihan","payment.allocate",{paymentId:pay.id,lines:[{invoiceId:invoice.id,amount:total}]});s=await state("penagihan");assert.equal(s.allocations.filter(a=>a.invoiceId===invoice.id).reduce((n,a)=>n+a.amount,0),total);assert.equal(s.movements.filter(m=>m.sourceId===sh.id&&m.type==="dispatch").reduce((n,m)=>n+m.qty,0),-2);
for(const [kind,id] of [["shipment",sh.id],["invoice",invoice.id],["report",new Date().toISOString().slice(0,10)]]){const r=await request(kind==="report"?"laporan":"pic-a",`/api/documents/${kind}/${id}`);assert.equal(r.status,200,await r.clone().text());assert.ok((await r.text()).includes("DEMO CAPSTONE"));}
assert.equal((await request("pic-b",`/api/documents/invoice/${invoice.id}`)).status,404);assert.equal((await request("kurir","/api/reports")).status,403);assert.equal((await request("laporan","/api/reports")).status,200);
const forbidden=await request("pic-a","/api/commands",{method:"POST",headers:{"content-type":"application/json",origin:"https://example.invalid"},body:JSON.stringify({id:crypto.randomUUID(),type:"payment.record",data:{amount:1}})});assert.equal(forbidden.status,403);await login("pic-a");assert.ok((await state("pic-a")).invoices.some(i=>i.id===invoice.id));
console.log(JSON.stringify({passed:true,checks:["Alur lengkap HTTP dengan libSQL","Dispatch paralel idempotent","Lampiran privat tersimpan dan terisolasi","Cetak SJ/invoice/laporan","CSV dengan hak akses","Proteksi lintas origin","Data tetap ada setelah login ulang"],orderId:order.id,shipmentId:sh.id,invoiceId:invoice.id,total},null,2));
