"use client";
import { PurchaseEditor } from "./purchase-editor";
import { useState, type ReactNode } from "react";
import { Plus, FileDown, Printer, Paperclip } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Field, FieldLabel } from "@/components/ui/field";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { validReportDate } from "@/lib/domain/operations-views";
import type { OperationsQueryProps } from "./inventory-workspace";
import type { QueryPatch } from "./use-workspace-navigation";
import { ROLE_LABELS, type Role } from "@/lib/domain/accounts";
import { ACCOUNTS, type Shipment } from "@/lib/domain/model";
import { get,sum,money,today,financialReport,invoiceTotal,invoiceBalance,paymentAvailable } from "@/lib/domain/selectors";
import { Status,type WorkspaceContext } from "./workspace";
import { toast } from "sonner";
import { SalesRegister } from "./sales-register";

const label=(status:string)=>({draft:"Draf",ordered:"Dipesan",complete:"Lengkap",none:"Belum diajukan",requested:"Menunggu persetujuan",approved:"Disetujui",disbursed:"Dana tersedia",quarantined:"Karantina",accepted:"Diterima",rejected:"Ditolak",paid:"Dibayar",open:"Terbuka",review:"Dalam tinjauan",closed:"Ditutup"}[status]||status);
function periodLabel(month:string){return new Date(month+"-01T12:00:00+07:00").toLocaleDateString("id-ID",{month:"long",year:"numeric",timeZone:"Asia/Jakarta"});}
const moneyHeaders=new Set(["Nilai","Harga beli","Debit","Kredit","Saldo debit / (kredit)","Nilai invoice","Sisa piutang","Belum dialokasikan","Koreksi"]);
function Table({heads,children,numericColumns=[]}:{heads:string[];children:ReactNode;numericColumns?:number[]}){return <div className="table-scroll"><table className="data-table"><thead><tr>{heads.map((h,i)=><th key={i} className={moneyHeaders.has(h)||numericColumns.includes(i)?"numeric":undefined}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
function Note({children}:{children:ReactNode}){return <p className="module-note">{children}</p>;}
export function DocumentLink({kind,id,children}:{kind:string;id:string;children?:ReactNode}){return <a className="document-link" href={`/api/documents/${kind}/${encodeURIComponent(id)}`} target="_blank" rel="noreferrer"><Printer size={15}/>{children||"Cetak / PDF"}</a>;}

export function Attachments({ctx,scope,targetId}:{ctx:WorkspaceContext;scope:string;targetId:string}){
 const [busy,setBusy]=useState(false);const items=ctx.s.attachments.filter(a=>a.scope===scope&&a.targetId===targetId);
 async function upload(file:File){setBusy(true);try{const form=new FormData();form.set("file",file);form.set("scope",scope);form.set("targetId",targetId);const response=await fetch("/api/attachments",{method:"POST",body:form});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error);await ctx.refresh();toast.success("Lampiran tersimpan.");}catch(err){toast.error(err instanceof Error?err.message:"Lampiran belum tersimpan.");}finally{setBusy(false);}}
 const canUpload=scope==="payment"?["pic","penagihan"].includes(ctx.actor.role):scope==="receipt"?["pic","staf","kurir"].includes(ctx.actor.role):scope==="expense"?["staf","kurir","kepala"].includes(ctx.actor.role):false;
 if(!canUpload&&!items.length)return null;
 return <div className="attachment-list">{items.map(a=><a href={`/api/attachments/${a.id}`} key={a.id} target="_blank" rel="noreferrer"><Paperclip size={14}/>{a.name}</a>)}{canUpload&&<label className="upload-label"><Paperclip size={14}/>{busy?"Mengunggah…":"Unggah bukti"}<input aria-label={`Unggah bukti ${scope}`} type="file" accept="image/png,image/jpeg,application/pdf" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value="";}}/></label>}{canUpload&&<small>PNG, JPG, atau PDF · Maksimal 4 MB</small>}</div>;
}

export function Procurement(ctx:WorkspaceContext){const {s,actor,ask}=ctx;
 const [creating,setCreating]=useState(false);
 return <div className="procurement-v6">{creating&&<PurchaseEditor ctx={ctx} close={()=>setCreating(false)}/>}<section className="panel ready-billing"><div><h2>Pesanan pemasok</h2><p>Pantau penerimaan barang, pembayaran, dan kebutuhan dana.</p></div>{["kepala","staf"].includes(actor.role)&&<Button onClick={()=>setCreating(true)}><Plus/>Buat pengadaan</Button>}</section>{!s.purchases.length&&<section className="panel"><Empty><EmptyHeader><EmptyTitle>Belum ada pengadaan</EmptyTitle><EmptyDescription>Pengadaan yang dibuat Staf atau Kepala Toko akan tampil di sini, beserta penerimaan dan pembayaran pemasoknya.</EmptyDescription></EmptyHeader></Empty></section>}{[...s.purchases].reverse().map(p=>{const ls=s.purchaseLines.filter(l=>l.purchaseId===p.id),total=sum(ls.map(l=>l.qty*l.cost)),received=sum(ls.map(l=>l.received*l.cost)),paid=sum(s.supplierPayments.filter(x=>x.purchaseId===p.id).map(x=>x.amount)),remaining=ls.filter(l=>l.received<l.qty),canManage=["OMI reguler","DDO"].includes(p.kind)?["staf","kepala"].includes(actor.role):actor.role==="kepala",canPay=["OMI reguler","DDO"].includes(p.kind)?actor.role==="staf":actor.role==="kepala";return <section className="panel" key={p.id}><div className="panel-title"><div><h2>{p.number} · {p.kind}</h2><p>{get(s.suppliers,p.supplierId).name} · {p.date}{p.orderId&&` · ${get(s.orders,p.orderId).number}`}</p></div><Status text={label(p.status)}/></div><Table heads={["Barang","Dipesan","Diterima","Harga beli","Nilai"]}>{ls.map(l=><tr key={l.id}><td className="cell-description">{get(s.products,l.productId).name}</td><td>{l.qty}</td><td>{l.received}</td><td className="numeric">{money(l.cost)}</td><td className="numeric">{money(l.qty*l.cost)}</td></tr>)}</Table><div className="detail-totals"><span>Pesanan <b>{money(total)}</b></span><span>Sudah dibayar <b>{money(paid)}</b></span><span>Utang atas penerimaan <b>{money(Math.max(0,received-paid))}</b></span><span>Uang muka <b>{money(Math.max(0,paid-received))}</b></span></div>{p.note&&<Note>{p.note}</Note>}{p.kind==="Pasar Kering"&&<Note>Dana internal: <Status text={label(p.fundingStatus)}/> {money(p.fundingAmount)}</Note>}<div className="delivery-actions">
 {p.kind==="Pasar Kering"&&actor.role==="kepala"&&p.fundingStatus==="none"&&<Button variant="outline" onClick={()=>ask({title:"Ajukan dana Pasar Kering",description:"Dana ditinjau oleh Pimpinan Unit sebelum disiapkan Penagihan.",type:"funding.request",data:{id:p.id},fields:[{key:"amount",label:"Kebutuhan dana (Rp)",type:"number",value:total,min:total}]})}>Ajukan dana</Button>}
 {p.fundingStatus==="requested"&&actor.role==="pimpinan"&&<Button onClick={()=>ask({title:"Setujui kebutuhan dana",description:`Alokasi internal simulasi ${money(p.fundingAmount)}.`,type:"funding.approve",data:{id:p.id},fields:[]})}>Setujui dana</Button>}
 {p.fundingStatus==="approved"&&actor.role==="penagihan"&&<Button onClick={()=>ask({title:"Siapkan dana pembelian",description:"Mencatat dana internal tersedia untuk belanja; tidak mengirim uang nyata.",type:"funding.disburse",data:{id:p.id},fields:[]})}>Siapkan dana</Button>}
 {canManage&&p.status==="draft"&&<Button disabled={p.kind==="Pasar Kering"&&p.fundingStatus!=="disbursed"} onClick={()=>ask({title:"Konfirmasi pesanan pemasok",description:"Pesanan dikonfirmasi secara simulasi. Selanjutnya catat barang yang benar-benar diterima.",type:"purchase.confirm",data:{id:p.id},fields:[]})}>Konfirmasi pemesanan</Button>}
 {actor.role==="staf"&&p.status==="ordered"&&<Button onClick={()=>ask({title:"Terima barang pemasok",description:"Jumlah aktual menambah batch persediaan. Sisa tetap menjadi pesanan terbuka.",type:"purchase.receive",data:{id:p.id},fields:remaining.flatMap(l=>[{key:`q-${l.id}`,group:get(s.products,l.productId).name,label:"Jumlah diterima",type:"number" as const,value:l.qty-l.received,min:0,max:l.qty-l.received},{key:`e-${l.id}`,group:get(s.products,l.productId).name,label:"Kedaluwarsa",type:"date" as const,optional:true},{key:`b-${l.id}`,group:get(s.products,l.productId).name,label:"Kode batch pemasok",optional:true}]),map:v=>({lines:remaining.filter(l=>Number(v[`q-${l.id}`])>0).map(l=>({purchaseLineId:l.id,qty:Number(v[`q-${l.id}`]),expiry:v[`e-${l.id}`],code:v[`b-${l.id}`]}))}),label:"Catat penerimaan"})}>Terima barang</Button>}
 {canPay&&p.status!=="draft"&&paid<total&&<Button variant="outline" onClick={()=>ask({title:"Catat pembayaran pemasok",description:"Pembayaran sebelum penerimaan menjadi uang muka. Referensi invoice atau SPH disimpan untuk penelusuran.",type:"supplier.pay",data:{purchaseId:p.id},fields:[{key:"amount",label:"Nilai pembayaran (Rp)",type:"number",value:total-paid,max:total-paid},{key:"reference",label:"Referensi invoice / SPH / transfer simulasi"}]})}>Bayar / uang muka</Button>}
 <DocumentLink kind="purchase" id={p.id}/></div></section>;})}<ExpenseCenter {...ctx}/></div>;
}

export function ExpenseCenter(ctx:WorkspaceContext){const {s,actor,ask}=ctx;return <section className="panel"><div className="panel-title"><div><h2>Biaya operasional</h2><p>Biaya selalu ditautkan ke pengiriman atau pengadaan.</p></div>{["staf","kurir","kepala"].includes(actor.role)&&<Button variant="outline" onClick={()=>ask({title:"Ajukan biaya operasional",description:"Masukkan bukti dan rincian biaya untuk persetujuan Pimpinan Unit. Tidak ada transfer dana nyata.",type:"expense.create",fields:[{key:"shipmentId",label:"Surat Jalan terkait",type:"select",optional:true,options:s.shipments.map(sh=>({value:sh.id,label:sh.number}))},...(actor.role!=="kurir"?[{key:"purchaseId",label:"Atau pengadaan terkait",type:"select" as const,optional:true,options:s.purchases.map(p=>({value:p.id,label:p.number}))}]:[]),{key:"category",label:"Jenis biaya",type:"select",options:["Transportasi","Parkir","Pengiriman","Administrasi"].map(k=>({value:k,label:k}))},{key:"amount",label:"Nilai biaya (Rp)",type:"number"},{key:"description",label:"Keterangan",type:"textarea"}]})}><Plus/>Ajukan biaya</Button>}</div><Table heads={["Biaya / dokumen","Nilai","Status","Bukti & tindakan"]}>{s.expenses.map(e=><tr key={e.id}><td className="cell-description"><strong>{e.category}</strong><small>{e.description}</small><small>{e.shipmentId?s.shipments.find(sh=>sh.id===e.shipmentId)?.number:s.purchases.find(p=>p.id===e.purchaseId)?.number}</small></td><td className="numeric">{money(e.amount)}</td><td><Status text={label(e.status)}/></td><td><Attachments ctx={ctx} scope="expense" targetId={e.id}/>{e.status==="requested"&&actor.role==="pimpinan"&&<Button size="sm" onClick={()=>ask({title:"Setujui penggantian biaya",description:`${e.category}: ${money(e.amount)}.`,type:"expense.approve",data:{id:e.id},fields:[]})}>Setujui biaya</Button>}{e.status==="approved"&&actor.role==="penagihan"&&<Button size="sm" onClick={()=>ask({title:"Catat penggantian biaya",description:"Mencatat pengeluaran kas simulasi dan beban operasional.",type:"expense.pay",data:{id:e.id},fields:[]})}>Catat pembayaran</Button>}</td></tr>)}</Table>{!s.expenses.length&&<Note>Belum ada pengajuan biaya.</Note>}</section>;}

export function SettlementControls(ctx:WorkspaceContext){const {s,actor,ask}=ctx;return <>
 <section className="panel"><div className="panel-title"><div><h2>Nota kredit</h2><p>Koreksi tagihan melalui persetujuan; invoice asal tetap tersimpan.</p></div>{actor.role==="penagihan"&&<Button variant="outline" onClick={()=>ask({title:"Ajukan nota kredit",description:"Gunakan untuk koreksi nilai setelah finalisasi. Koreksi atas invoice lunas menjadi saldo divisi, bukan penerimaan kas baru.",type:"credit.request",fields:[{key:"invoiceId",label:"Invoice",type:"select",options:s.invoices.map(i=>({value:i.id,label:`${i.number} · ${money(invoiceTotal(s,i.id))}`}))},{key:"amount",label:"Nilai koreksi termasuk pajak simulasi (Rp)",type:"number"},{key:"reason",label:"Alasan / konfirmasi divisi",type:"textarea"}]})}><Plus/>Ajukan koreksi</Button>}</div><Table heads={["Invoice","Koreksi","Alasan","Status"]}>{s.credits.map(c=><tr key={c.id}><td>{get(s.invoices,c.invoiceId).number}</td><td className="numeric">{money(c.amount)}</td><td className="cell-description">{c.reason}</td><td>{c.status==="requested"&&actor.role==="pimpinan"?<Button size="sm" onClick={()=>ask({title:"Setujui nota kredit",description:`Koreksi ${money(c.amount)} beserta jurnal pembalik nilai penjualan.`,type:"credit.approve",data:{id:c.id},fields:[]})}>Setujui koreksi</Button>:<Status text={label(c.status)}/>}</td></tr>)}</Table>{!s.credits.length&&<Note>Belum ada nota kredit.</Note>}</section>
 <section className="panel"><div className="panel-title"><div><h2>Pengembalian saldo divisi</h2><p>Kelebihan dana dapat dialokasikan kembali atau diajukan pengembaliannya.</p></div>{actor.role==="penagihan"&&<Button variant="outline" onClick={()=>ask({title:"Ajukan pengembalian saldo",description:"Catat konfirmasi divisi. Pimpinan menyetujui sebelum pembayaran simulasi dicatat.",type:"refund.request",fields:[{key:"paymentId",label:"Sumber saldo",type:"select",options:s.payments.filter(p=>p.divisionId&&paymentAvailable(s,p.id)>0).map(p=>({value:p.id,label:`${p.reference||p.payer} · ${money(paymentAvailable(s,p.id))}`}))},{key:"amount",label:"Nilai pengembalian (Rp)",type:"number"},{key:"reason",label:"Konfirmasi divisi dan alasan",type:"textarea"}]})}>Ajukan pengembalian</Button>}</div><Table heads={["Pembayar","Jumlah","Alasan","Status"]} numericColumns={[1]}>{s.refunds.map(r=><tr key={r.id}><td className="cell-description">{get(s.payments,r.paymentId).payer}</td><td className="numeric">{money(r.amount)}</td><td className="cell-description">{r.reason}</td><td>{r.status==="requested"&&actor.role==="pimpinan"?<Button size="sm" onClick={()=>ask({title:"Setujui pengembalian dana",description:`Saldo ${money(r.amount)} dicadangkan untuk pengembalian.`,type:"refund.approve",data:{id:r.id},fields:[]})}>Setujui</Button>:r.status==="approved"&&actor.role==="penagihan"?<Button size="sm" onClick={()=>ask({title:"Catat pengembalian dana",description:"Mencatat pengeluaran simulasi dan mengurangi saldo titipan divisi.",type:"refund.pay",data:{id:r.id},fields:[]})}>Catat pembayaran</Button>:<Status text={label(r.status)}/>}</td></tr>)}</Table>{!s.refunds.length&&<Note>Belum ada pengajuan pengembalian saldo.</Note>}</section></>;}

export function ShipmentExtras({ctx,shipment:sh}:{ctx:WorkspaceContext;shipment:Shipment}){const {s,actor,ask}=ctx;const ls=s.shipmentLines.filter(l=>l.shipmentId===sh.id);return <><div className="delivery-actions delivery-documents"><DocumentLink kind="shipment" id={sh.id}/>{actor.role==="staf"&&sh.status==="ready"&&<Button variant="outline" onClick={()=>ask({title:"Batalkan Surat Jalan",description:"Nomor dan riwayat dipertahankan. Reservasi dapat dipakai untuk penyiapan ulang.",type:"shipment.cancel",data:{id:sh.id},fields:[{key:"reason",label:"Alasan",type:"textarea"}]})}>Batalkan Surat Jalan</Button>}{["kurir","staf"].includes(actor.role)&&sh.status==="dispatched"&&<><Button variant="outline" onClick={()=>ask({title:"Catat bukti pengantaran",description:"Simpan nama penerima dan catatan. Unggah lampiran pada bagian bukti di bawah.",type:"shipment.proof",data:{id:sh.id},fields:[{key:"receiver",label:"Nama penerima"},{key:"evidence",label:"Catatan bukti serah terima"}]})}>Catat bukti</Button><Button variant="outline" onClick={()=>ask({title:"Catat gagal kirim",description:"Barang kembali dicatat oleh Staf Toko sebelum pengiriman susulan.",type:"shipment.fail",data:{id:sh.id},fields:[{key:"reason",label:"Alasan gagal kirim",type:"textarea"}]})}>Gagal kirim</Button></>}{actor.role==="pic"&&sh.status==="received"&&ls.some(l=>!l.finalized&&l.accepted>0)&&<Button variant="outline" onClick={()=>ask({title:"Ajukan komplain barang",description:"Jumlah yang dikomplain dikeluarkan dari jumlah siap tagih sampai penanganan selesai.",type:"complaint.create",fields:[{key:"shipmentLineId",label:"Barang",type:"select",options:ls.filter(l=>!l.finalized&&l.accepted>0).map(l=>({value:l.id,label:`${get(s.products,get(s.orderLines,l.orderLineId).productId).name} · diterima ${l.accepted}`}))},{key:"qty",label:"Jumlah bermasalah",type:"number"},{key:"reason",label:"Rincian komplain",type:"textarea"}]})}>Ajukan komplain</Button>}</div>{(["pic","staf","kurir"].includes(actor.role)||s.attachments.some(a=>a.scope==="receipt"&&a.targetId===sh.id))&&<div className="module-note delivery-evidence"><Attachments ctx={ctx} scope="receipt" targetId={sh.id}/></div>}</>;}

export function Reports({query: suppliedQuery,onQueryChange: suppliedChange,...ctx}:WorkspaceContext & Partial<OperationsQueryProps>){
 const {s}=ctx;
 const [localQuery,setLocalQuery]=useState("");
 const query=suppliedQuery||new URLSearchParams(localQuery);
 const onQueryChange=suppliedChange||((patch:QueryPatch)=>setLocalQuery(current=>{const next=new URLSearchParams(current);for(const [key,value] of Object.entries(patch)){if(value===null||value==="")next.delete(key);else next.set(key,value);}return next.toString();}));
 const tab=["sales","finance","journals","activity"].includes(query.get("reportTab")||"")?query.get("reportTab")!:"sales";
 const end=validReportDate(query.get("reportAsOf"),today()),report=financialReport(s,end);
 const balance=(code:string)=>{const a=report.accounts.find(account=>account.code===code)!;return a.debit-a.credit;};
 const revenue=-balance("sales"),expense=balance("expense"),cogs=balance("cogs"),margin=revenue-cogs-expense-balance("adjustment");
 const journals=[...report.journals].reverse(),journalPages=Math.max(1,Math.ceil(journals.length/12)),journalPage=Math.min(Math.max(1,Math.floor(Number(query.get("journalPage"))||1)),journalPages);
 const journalLines=new Map<string,typeof s.journalLines>();
 for(const line of s.journalLines){const group=journalLines.get(line.journalId)||[];group.push(line);journalLines.set(line.journalId,group);}
 const audits=[...s.audits].reverse().slice(0,100),auditPages=Math.max(1,Math.ceil(audits.length/20)),auditPage=Math.min(Math.max(1,Math.floor(Number(query.get("auditPage"))||1)),auditPages);
 const shownJournals=journals.slice((journalPage-1)*12,journalPage*12),shownAudits=audits.slice((auditPage-1)*20,auditPage*20);
 const asOf=(id:string)=><section className="panel"><div className="panel-title"><div><h2>{id==="finance"?"Posisi keuangan":"Jurnal kumulatif"}</h2><p>Seluruh jurnal dari saldo awal sampai tanggal pilihan. Angka ini bukan transaksi dalam satu rentang bulan.</p></div></div><div className="ops-asof"><Field><FieldLabel htmlFor={id+"-asof"}>Saldo sampai tanggal</FieldLabel><Input id={id+"-asof"} type="date" value={end} onChange={event=>onQueryChange({reportAsOf:event.target.value||null,journalPage:null})}/></Field><div className="ops-row-actions"><a className="document-link" href={"/api/reports?end="+encodeURIComponent(end)}><FileDown size={16}/>CSV neraca & jurnal</a><DocumentLink kind="report" id={end}>Cetak keuangan</DocumentLink></div><p>Ekspor mencakup neraca dan seluruh jurnal sampai {end}.</p></div></section>;
 const pagination=(page:number,pages:number,key:string,count:number)=><div className="ops-pagination"><p>{count} catatan</p><div><Button variant="outline" disabled={page===1} onClick={()=>onQueryChange({[key]:String(page-1)})}>Sebelumnya</Button><span>Halaman {page} / {pages}</span><Button variant="outline" disabled={page===pages} onClick={()=>onQueryChange({[key]:String(page+1)})}>Berikutnya</Button></div></div>;
 return <Tabs className="reports-v6 ops-workspace" value={tab} onValueChange={value=>onQueryChange({reportTab:value})}><TabsList className="ops-tabs" aria-label="Bagian laporan"><TabsTrigger value="sales">Penjualan</TabsTrigger><TabsTrigger value="finance">Keuangan</TabsTrigger><TabsTrigger value="journals">Jurnal</TabsTrigger><TabsTrigger value="activity">Aktivitas</TabsTrigger></TabsList>
 <TabsContent value="sales"><SalesRegister {...ctx} query={query} onQueryChange={onQueryChange}/></TabsContent>
 <TabsContent value="finance"><div className="ops-section-stack">{asOf("finance")}<div className="metric-grid">{[["Penjualan bersih",revenue],["Harga pokok",cogs],["Beban operasional",expense],["Hasil operasional",margin]].map(([name,value])=><div className="metric-card" key={String(name)}><div><span>{name}</span></div><strong>{money(Number(value))}</strong></div>)}</div>
 <section className="panel"><div className="panel-title"><h2>Neraca saldo</h2><Status text={report.debit===report.credit?"Seimbang":"Perlu rekonsiliasi"}/></div><div className="ops-desktop-table"><Table heads={["Akun","Debit","Kredit","Saldo debit / (kredit)"]}>{report.accounts.map(a=><tr key={a.code}><td>{a.name}</td><td className="numeric">{money(a.debit)}</td><td className="numeric">{money(a.credit)}</td><td className="numeric">{money(a.debit-a.credit)}</td></tr>)}<tr><td><strong>Total</strong></td><td className="numeric"><strong>{money(report.debit)}</strong></td><td className="numeric"><strong>{money(report.credit)}</strong></td><td className="numeric">{money(report.debit-report.credit)}</td></tr></Table></div><div className="ops-mobile-list">{report.accounts.map(a=><article className="ops-record" key={a.code}><h3>{a.name}</h3><dl className="ops-facts"><div><dt>Debit</dt><dd>{money(a.debit)}</dd></div><div><dt>Kredit</dt><dd>{money(a.credit)}</dd></div><div><dt>Saldo debit / (kredit)</dt><dd>{money(a.debit-a.credit)}</dd></div></dl></article>)}<div className="ops-results-heading"><p>Total debit / kredit</p><strong>{money(report.debit)} / {money(report.credit)}</strong></div></div></section>
 <details className="panel ops-disclosure"><summary>Piutang divisi saat ini</summary><p className="module-note">Daftar operasional terbaru. Transaksi setelah tanggal laporan dapat mengubah saldo ini; daftar ini tidak masuk ekspor neraca dan jurnal.</p><div className="ops-desktop-table"><Table heads={["Divisi","Nilai invoice","Sisa piutang","Belum dialokasikan"]}>{s.divisions.map(d=><tr key={d.id}><td>{d.name}</td><td className="numeric">{money(sum(s.invoices.filter(i=>i.divisionId===d.id).map(i=>invoiceTotal(s,i.id))))}</td><td className="numeric">{money(sum(s.invoices.filter(i=>i.divisionId===d.id).map(i=>invoiceBalance(s,i.id))))}</td><td className="numeric">{money(sum(s.payments.filter(p=>p.divisionId===d.id).map(p=>paymentAvailable(s,p.id))))}</td></tr>)}</Table></div><div className="ops-mobile-list">{s.divisions.map(d=><article className="ops-record" key={d.id}><h3>{d.name}</h3><dl className="ops-facts"><div><dt>Nilai invoice</dt><dd>{money(sum(s.invoices.filter(i=>i.divisionId===d.id).map(i=>invoiceTotal(s,i.id))))}</dd></div><div><dt>Sisa piutang</dt><dd>{money(sum(s.invoices.filter(i=>i.divisionId===d.id).map(i=>invoiceBalance(s,i.id))))}</dd></div><div><dt>Belum dialokasikan</dt><dd>{money(sum(s.payments.filter(p=>p.divisionId===d.id).map(p=>paymentAvailable(s,p.id))))}</dd></div></dl></article>)}</div></details>
 <details className="panel ops-disclosure"><summary>Biaya operasional · {s.expenses.filter(e=>e.status!=="paid").length} belum dibayar</summary><ExpenseCenter {...ctx}/></details></div></TabsContent>
 <TabsContent value="journals"><div className="ops-section-stack">{asOf("journals")}<section className="panel"><div className="panel-title"><div><h2>Jurnal transaksi</h2><p>{journals.length} jurnal sampai {end}. Satu jurnal dapat memiliki beberapa baris akun.</p></div></div><div className="ops-desktop-table"><Table heads={["Tanggal / transaksi","Akun","Debit","Kredit"]}>{shownJournals.flatMap(j=>(journalLines.get(j.id)||[]).map((line,index)=><tr key={line.id}><td className="cell-description">{index===0&&<><strong>{j.date}</strong><small>{j.description}</small></>}</td><td>{ACCOUNTS[line.account]}</td><td className="numeric">{line.debit?money(line.debit):"—"}</td><td className="numeric">{line.credit?money(line.credit):"—"}</td></tr>))}</Table></div><div className="ops-mobile-list">{shownJournals.map(j=><article className="ops-record" key={j.id}><h3>{j.description}</h3><p className="ops-record-note">{j.date}</p><div className="ops-journal-lines">{(journalLines.get(j.id)||[]).map(line=><div key={line.id}><span>{ACCOUNTS[line.account]}</span><strong>{line.debit?"Debit":"Kredit"} {money(line.debit||line.credit)}</strong></div>)}</div></article>)}</div>{!journals.length&&<Empty><EmptyHeader><EmptyTitle>Belum ada jurnal pada tanggal ini</EmptyTitle><EmptyDescription>Pilih tanggal setelah saldo awal atau transaksi dicatat.</EmptyDescription></EmptyHeader></Empty>}{!!journals.length&&pagination(journalPage,journalPages,"journalPage",journals.length)}</section></div></TabsContent>
 <TabsContent value="activity"><section className="panel"><div className="panel-title"><div><h2>Jejak aktivitas</h2><p>Maksimal 100 aktivitas terbaru sesuai hak akses. Nama petugas ditampilkan jika tersedia bagi peran Anda.</p></div></div><div className="ops-desktop-table"><Table heads={["Waktu","Petugas","Tindakan"]}>{shownAudits.map(a=><tr key={a.id}><td>{new Date(a.at).toLocaleString("id-ID",{timeZone:"Asia/Jakarta"})}</td><td>{s.users.find(u=>u.id===a.actorId)?.name??"Akun lain"}</td><td className="cell-description">{a.description}</td></tr>)}</Table></div><div className="ops-mobile-list">{shownAudits.map(a=><article className="ops-record" key={a.id}><h3>{a.description}</h3><p className="ops-record-note">{new Date(a.at).toLocaleString("id-ID",{timeZone:"Asia/Jakarta"})}</p><p className="ops-record-note">Petugas: {s.users.find(u=>u.id===a.actorId)?.name??"Akun lain"}</p></article>)}</div>{!audits.length&&<Empty><EmptyHeader><EmptyTitle>Belum ada aktivitas yang dapat ditampilkan</EmptyTitle><EmptyDescription>Aktivitas operasional akan muncul setelah tindakan dicatat.</EmptyDescription></EmptyHeader></Empty>}{!!audits.length&&pagination(auditPage,auditPages,"auditPage",audits.length)}</section></TabsContent>
 </Tabs>;
}

export function Periods({s,actor,ask}:WorkspaceContext){return <><section className="panel ready-billing"><div><h2>Laporan bulanan</h2><p>Tinjau dan setujui laporan sebelum menutup periode.</p></div>{["laporan","penagihan"].includes(actor.role)&&<Button onClick={()=>ask({title:"Ajukan laporan bulanan",description:"Laporan diajukan untuk periode YYYY-MM. Transaksi tambahan membatalkan persetujuan versi sebelumnya.",type:"period.submit",fields:[{key:"month",label:"Bulan laporan (YYYY-MM)",value:today().slice(0,7)}]})}>Ajukan laporan</Button>}</section><section className="panel"><Table heads={["Periode","Versi","Status","Persetujuan","Tindakan"]}>{[...s.periods].sort((a,b)=>b.id.localeCompare(a.id)).map(p=><tr key={p.id}><td><strong>{periodLabel(p.id)}</strong></td><td>{p.revision}</td><td><Status text={label(p.status)}/></td><td>{p.approvedBy&&["approved","closed"].includes(p.status)?(s.users.find(u=>u.id===p.approvedBy)?.name??"Akun lain"):"Belum disetujui"}{p.closedAt&&<small>Dikunci {new Date(p.closedAt).toLocaleString("id-ID")}</small>}</td><td><div className="row-actions">{actor.role==="pimpinan"&&p.status==="review"&&<Button size="sm" onClick={()=>ask({title:"Setujui versi laporan",description:`${periodLabel(p.id)}, versi ${p.revision}. Periksa laporan sebelum menyetujui.`,type:"period.approve",data:{id:p.id},fields:[]})}>Setujui versi {p.revision}</Button>}{actor.role==="akuntansi"&&p.status==="approved"&&<Button size="sm" onClick={()=>ask({title:"Tutup dan posting periode",description:`${periodLabel(p.id)} akan dikunci. Koreksi berikutnya dicatat pada periode terbuka; laporan periode ini tetap tersimpan.`,type:"period.close",data:{id:p.id},fields:[],label:"Tutup periode"})}>Posting & tutup</Button>}<DocumentLink kind="period" id={p.id}>{p.status==="closed"?"Snapshot tertutup":"Tinjau laporan"}</DocumentLink></div></td></tr>)}</Table></section></>;}

export function AccountSettings({s,actor,ask}:WorkspaceContext){return <><section className="panel"><div className="panel-title"><div><h2>Akun & hak akses</h2><p>Perubahan hak akses berlaku juga untuk akun yang sedang masuk.</p></div></div><Table heads={["Nama","Peran","Divisi","Status","Tindakan"]}>{s.users.map(u=><tr key={u.id}><td className="cell-description"><strong>{u.name}</strong><small>{u.email}</small></td><td>{ROLE_LABELS[u.role]}</td><td>{s.divisions.find(d=>d.id===u.divisionId)?.name||"Lintas unit"}</td><td><Status text={u.active?"Aktif":"Nonaktif"}/></td><td><Button size="sm" variant="outline" disabled={u.id===actor.id} onClick={()=>ask({title:"Atur hak akses akun",description:"Tentukan peran, divisi, dan status akun. PIC mendapat akses ke divisinya; akun nonaktif tidak dapat melanjutkan penggunaan portal.",type:"admin.user",data:{id:u.id},fields:[{key:"role",label:"Peran",type:"select",value:u.role,options:Object.entries(ROLE_LABELS).map(([value,label])=>({value,label}))},{key:"divisionId",label:"Divisi (wajib untuk PIC)",type:"select",optional:true,value:u.divisionId||"",options:s.divisions.map(d=>({value:d.id,label:d.name}))},{key:"active",label:"Akses akun",type:"select",value:String(u.active),options:[{value:"true",label:"Aktif"},{value:"false",label:"Nonaktif"}]}],map:v=>({role:v.role as Role,divisionId:v.divisionId,active:v.active==="true"})})}>Atur akun</Button></td></tr>)}</Table><Note>Pengaturan akun yang sedang Anda gunakan tidak dapat diubah dari halaman ini.</Note></section><section className="panel"><div className="panel-title"><h2>Data divisi</h2><Button variant="outline" onClick={()=>ask({title:"Tambah divisi",description:"Isi nama, kode, dan alamat penerimaan. Akun PIC dapat dikaitkan melalui pengaturan akun.",type:"admin.division",fields:[{key:"name",label:"Nama divisi"},{key:"code",label:"Kode divisi"},{key:"address",label:"Alamat penerimaan",type:"textarea"}]})}><Plus/>Tambah divisi</Button></div><Table heads={["Divisi","Kode","Alamat"]}>{s.divisions.map(d=><tr key={d.id}><td>{d.name}</td><td>{d.code}</td><td className="cell-description">{d.address}</td></tr>)}</Table></section><section className="panel"><div className="panel-title"><h2>Daftar pemasok</h2><Button variant="outline" onClick={()=>ask({title:"Tambah pemasok",description:"Isi nama pemasok dan jalur pengadaannya.",type:"admin.supplier",fields:[{key:"name",label:"Nama pemasok"},{key:"category",label:"Kategori / jalur pengadaan"}]})}><Plus/>Tambah pemasok</Button></div><Table heads={["Nama pemasok","Kategori"]}>{s.suppliers.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.category}</td></tr>)}</Table></section></>;}
