import { sql } from "drizzle-orm";
import { sqliteTable, text, integer, check, uniqueIndex } from "drizzle-orm/sqlite-core";
const record = () => ({ id:text("id").primaryKey(), payload:text("payload").notNull() });
export const divisions=sqliteTable("divisions",record());
export const users=sqliteTable("users",{...record(),divisionId:text("division_id").references(()=>divisions.id),role:text("role").notNull()});
export const credentials=sqliteTable("credentials",{userId:text("user_id").primaryKey().references(()=>users.id),salt:text("salt").notNull(),hash:text("hash").notNull()});
export const sessions=sqliteTable("sessions",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>users.id),expiresAt:integer("expires_at").notNull()});
export const products=sqliteTable("products",{...record(),sku:text("sku").notNull().unique()});
export const suppliers=sqliteTable("suppliers",record());
export const batches=sqliteTable("batches",{...record(),productId:text("product_id").notNull().references(()=>products.id),qty:integer("qty").notNull(),held:integer("held").notNull()},t=>[check("batch_quantity",sql`${t.qty}>=0 AND ${t.held}>=0 AND ${t.held}<=${t.qty}`)]);
export const orders=sqliteTable("orders",{...record(),divisionId:text("division_id").notNull().references(()=>divisions.id),number:text("number").notNull().unique()});
export const orderLines=sqliteTable("order_lines",{...record(),orderId:text("order_id").notNull().references(()=>orders.id),productId:text("product_id").notNull().references(()=>products.id)});
export const reservations=sqliteTable("reservations",{...record(),orderLineId:text("order_line_id").notNull().references(()=>orderLines.id),batchId:text("batch_id").notNull().references(()=>batches.id),qty:integer("qty").notNull()},t=>[check("reservation_quantity",sql`${t.qty}>=0`)]);
export const substitutions=sqliteTable("substitutions",{...record(),orderLineId:text("order_line_id").notNull().references(()=>orderLines.id),productId:text("product_id").notNull().references(()=>products.id)});
export const shipments=sqliteTable("shipments",{...record(),orderId:text("order_id").notNull().references(()=>orders.id),courierId:text("courier_id").notNull().references(()=>users.id),number:text("number").notNull().unique()});
export const shipmentLines=sqliteTable("shipment_lines",{...record(),shipmentId:text("shipment_id").notNull().references(()=>shipments.id),orderLineId:text("order_line_id").notNull().references(()=>orderLines.id),batchId:text("batch_id").notNull().references(()=>batches.id)});
export const complaints=sqliteTable("complaints",{...record(),shipmentId:text("shipment_id").notNull().references(()=>shipments.id),shipmentLineId:text("shipment_line_id").notNull().references(()=>shipmentLines.id),divisionId:text("division_id").notNull().references(()=>divisions.id)});
export const invoices=sqliteTable("invoices",{...record(),divisionId:text("division_id").notNull().references(()=>divisions.id),number:text("number").notNull().unique()});
export const invoiceLines=sqliteTable("invoice_lines",{...record(),invoiceId:text("invoice_id").notNull().references(()=>invoices.id),shipmentLineId:text("shipment_line_id").notNull().references(()=>shipmentLines.id)},t=>[uniqueIndex("invoice_source_once").on(t.shipmentLineId)]);
export const payments=sqliteTable("payments",{...record(),divisionId:text("division_id").references(()=>divisions.id)});
export const allocations=sqliteTable("allocations",{...record(),paymentId:text("payment_id").notNull().references(()=>payments.id),invoiceId:text("invoice_id").notNull().references(()=>invoices.id)});
export const credits=sqliteTable("credits",{...record(),invoiceId:text("invoice_id").notNull().references(()=>invoices.id)});
export const refunds=sqliteTable("refunds",{...record(),paymentId:text("payment_id").notNull().references(()=>payments.id)});
export const purchases=sqliteTable("purchases",{...record(),supplierId:text("supplier_id").notNull().references(()=>suppliers.id),orderId:text("order_id").references(()=>orders.id),number:text("number").notNull().unique()});
export const purchaseLines=sqliteTable("purchase_lines",{...record(),purchaseId:text("purchase_id").notNull().references(()=>purchases.id),productId:text("product_id").notNull().references(()=>products.id)});
export const supplierPayments=sqliteTable("supplier_payments",{...record(),purchaseId:text("purchase_id").notNull().references(()=>purchases.id)});
export const stockReturns=sqliteTable("stock_returns",{...record(),batchId:text("batch_id").notNull().references(()=>batches.id)});
export const stocktakes=sqliteTable("stocktakes",{...record(),batchId:text("batch_id").notNull().references(()=>batches.id)});
export const expenses=sqliteTable("expenses",{...record(),shipmentId:text("shipment_id").references(()=>shipments.id),purchaseId:text("purchase_id").references(()=>purchases.id)});
export const movements=sqliteTable("movements",{...record(),batchId:text("batch_id").notNull().references(()=>batches.id)});
export const journals=sqliteTable("journals",record());
export const journalLines=sqliteTable("journal_lines",{...record(),journalId:text("journal_id").notNull().references(()=>journals.id),debit:integer("debit").notNull(),credit:integer("credit").notNull()},t=>[check("journal_nonnegative",sql`${t.debit}>=0 AND ${t.credit}>=0`)]);
export const periods=sqliteTable("periods",record());
export const attachments=sqliteTable("attachments",{...record(),ownerId:text("owner_id").notNull().references(()=>users.id),divisionId:text("division_id").references(()=>divisions.id),shipmentId:text("shipment_id").references(()=>shipments.id)});
export const audits=sqliteTable("audits",{...record(),actorId:text("actor_id").notNull().references(()=>users.id)});
export const systemVersion=sqliteTable("system_version",{id:text("id").primaryKey(),version:integer("version").notNull()});
export const mutationGuards=sqliteTable("mutation_guards",{id:text("id").primaryKey(),valid:integer("valid").notNull()},t=>[check("concurrent_write_guard",sql`${t.valid}=1`)]);
export const commands=sqliteTable("commands",{id:text("id").primaryKey(),actorId:text("actor_id").notNull().references(()=>users.id),fingerprint:text("fingerprint").notNull(),result:text("result").notNull()});
